[
  {
    "user": {
      "id": 448124106,
      "username": "IGOR_Khodakovskiy",
      "first_name": "Igor",
      "last_name": "Khodakovskiy"
    },
    "query": "это тест. просто ответь \"Ok!\"",
    "response": "⚠️ Ошибка OpenAI: Error code: 404 - {'error': {'message': 'The model `gpt-4-turbo-preview` does not exist or you do not have access to it.', 'type': 'invalid_request_error', 'param': None, 'code': 'model_not_found'}}",
    "ai_service": "GPT-4 Turbo",
    "timestamp": "2025-07-28T13:52:45.518068"
  }
]